/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xat.h"

bool_t
xdr_Word (XDR *xdrs, Word *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Xat (XDR *xdrs, Xat *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->Xat_val, (u_int *) &objp->Xat_len, ~0,
		sizeof (Word), (xdrproc_t) xdr_Word))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Message (XDR *xdrs, Message *objp)
{
	register int32_t *buf;

	 if (!xdr_Word (xdrs, &objp->username))
		 return FALSE;
	 if (!xdr_Word (xdrs, &objp->text))
		 return FALSE;
	return TRUE;
}
