/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "xat.h"

void *
write_1_svc(Message *argp, struct svc_req *rqstp)
{
	static char * result;

	FILE * f = fopen("xat.txt", "a");

	fprintf(f, "%s: %s\n", argp->username, argp->text);

	fclose(f);

	return (void *) &result;
}

Xat *
getchat_1_svc(void *argp, struct svc_req *rqstp)
{
	static Xat  result;

	Word aux;
	FILE * f = fopen("xat.txt", "r");
	if (f != NULL) {

		result.Xat_len = 0;
		result.Xat_val = (Word *) malloc (sizeof(Word));
		result.Xat_val[result.Xat_len] = (char *) malloc (sizeof(char) * 200);
		fgets(result.Xat_val[result.Xat_len], 200, f);
		result.Xat_val[result.Xat_len][strlen(result.Xat_val[result.Xat_len]) - 1] = '\0';
		result.Xat_len++;

		while(!feof(f)) {

			result.Xat_val = realloc(result.Xat_val, sizeof(Word) * (result.Xat_len + 1));
			result.Xat_val[result.Xat_len] = (char *) malloc (sizeof(char) * 200);
			fgets(result.Xat_val[result.Xat_len], 200, f);
			result.Xat_val[result.Xat_len][strlen(result.Xat_val[result.Xat_len]) - 1] = '\0';
			result.Xat_len++;
		}

		result.Xat_len--;

		fclose(f);
	} else {
		result.Xat_len = 0;
	}

	return &result;
}
